### ISSUE TITLE
fm parameter is missing and automatically removed

### ISSUE THREAD

**Issue by intellix** [unsplash/ts-imgix#16]
We'd like AVIF images now, before waiting for December when they'll appear as part of format=auto.

It seems that this library doesn't allow the "fm" parameter: https://docs.imgix.com/apis/rendering/format/fm and removes it even if you force the type to any.

Example: `?fm=avif`

**Comment by OliverJAsh** [comment]
Fixed by https://github.com/unsplash/ts-imgix/commit/0ea003de67dc1f94b42db5aa7f885a925f7af19f

Released in https://github.com/unsplash/ts-imgix/releases/tag/v0.0.16
